sudo: required
language: cpp
python:
- '3.5'
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
      env: CC=clang CXX=clang++
    - os: linux
      dist: trusty
      compiler: gcc
      env: RUN_PYTEST=1

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y clang cmake g++ gcc libeigen3-dev swig3.0 libpython3.5-dev

script: ./build.sh
