language: cpp
python:
- '3.5'
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
      env: CC=clang CXX=clang++
    - os: linux
      dist: trusty
      compiler: gcc
      env: RUN_PYTEST=1

addons:
  apt:
    sources:
      - precise
    packages:
      - clang
      - cmake
      - g++
      - gcc
      - libeigen3-dev
      - swig3.0
      - libpython3.5-dev

script: ./build.sh
